# .streamlit/secrets.toml

# 1. A sua Connection String do MongoDB, com a palavra-passe correta e codificada
MONGO_CONNECTION_STRING = "mongodb+srv://timarcelomendes:B%40wzi280@cluster0.yjxkbq2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0y"

# 2. A CHAVE GERADA PELO SCRIPT PYTHON no Passo 1 (deve começar com gAAAAA...)
ENCRYPTION_KEY = "PNzlefaDnE-P21n46LxoZyvjDzGFGnMvmDA5ll-pdXU="

# 3. O NOVO TOKEN GERADO NO SITE DA JIRA no Passo 2 (deve começar com ATATT3x...)
JIRA_API_TOKEN = "ATATT3xFfGF0woWW1ZpuAhyjQQuk-E3jRwiKSd1IeWc0-y8BQKgadodcLdRI30Syf5CPQ-1KmQD30HnvDmHJhLg5gK3tQV6fLdvs7wVEuEZxxaed7zkQgUPirNXTWrgkBSe_j1pvybtKhzqnrLEG1vdPD3ZrKOsKbPUdqaqrgPDYjdyxIXQkKvQ=184367EE"

# As credenciais abaixo podem ser mantidas se forem as mesmas para a conexão com o Jira
JIRA_SERVER = "https://gauge-team.atlassian.net"
JIRA_USER_EMAIL = "mmmendes@stefanini.com"

[app_settings]
ALLOWED_DOMAINS = [
    "stefanini.com",
    "latam.stefanini.com",
    "gauge.haus"
]
# --- ADICIONE ESTA LISTA ---
ADMIN_EMAILS = [
    "mmmendes@stefanini.com",
    "ti.marcelomendes@gmail.com",
    "outro.admin@gauge.haus"
]

[gmail_smtp]
EMAIL_ADDRESS = "ti.marcelomendes@gmail.com"
EMAIL_PASSWORD = "ftyr wqly qgfa rnqc" 