# .streamlit/secrets.toml

JIRA_SERVER = "https://gauge-team.atlassian.net"
JIRA_USER_EMAIL = "mmmendes@stefanini.com"
JIRA_API_TOKEN = "ATATT3xFfGF0woWW1ZpuAhyjQQuk-E3jRwiKSd1IeWc0-y8BQKgadodcLdRI30Syf5CPQ-1KmQD30HnvDmHJhLg5gK3tQV6fLdvs7wVEuEZxxaed7zkQgUPirNXTWrgkBSe_j1pvybtKhzqnrLEG1vdPD3ZrKOsKbPUdqaqrgPDYjdyxIXQkKvQ=184367EE"